name: Block issue if linked to open issue

on:
  issue_comment:
    types: [created]
  issue:
    types: [closed]

jobs:
  block_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check for linked issues
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.issue;
            const linkedIssues = context.issue.body.matchAll(/#(\d+)/g);
            let blocked = false;
            for (const match of linkedIssues) {
              const linkedIssueNumber = match[1];
              const linkedIssue = await github.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: linkedIssueNumber,
              });
              if (linkedIssue.data.state !== 'closed') {
                blocked = true;
                break;
              }
            }
            if (blocked && context.payload.action === 'closed') {
              github.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'open',
              });
              github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `This issue cannot be closed until linked issue(s) are closed.`,
              });
            }
