name: Block issue if linked to open issue

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, closed]

jobs:
  block_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Block Issues
        uses: Levi-Lesches/blocking-issues@v2.0.1
        with:
          token: ${{ github.token }}
          use-label: blocked
      - name: Add blocked label
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              labels: ['blocked']
            })
